
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { RecentProfilesProvider } from "../app/context/RecentProfilesContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <RecentProfilesProvider>
            <div className="flex h-screen">
            {/* Sidebar with fixed height and width */}
            <div className="h-full fixed  top-0"> 
              <Sidebar />
            </div>

            {/* Main content area */}
            <main className="flex-grow overflow-y-auto overflow-x-hidden h-full "> {/* Main content with scroll */}
                {children}
              </main>
            
                
              
            
          </div>
        </RecentProfilesProvider>
        
      </body>
    </html>
  );
}
